export interface PartnerCourseSeed {
  partner_name: string;
  title: string;
  title_fr: string;
  description: string;
  description_fr: string;
  url: string;
  duration_minutes: number;
  level: 'beginner' | 'intermediate' | 'advanced';
  cost_type: 'free' | 'paid' | 'freemium';
  category: string;
  referral_url: string;
  featured: boolean;
}

export const partnerCourses: PartnerCourseSeed[] = [
  // DataGenius
  {
    partner_name: 'DataGenius',
    title: 'Excel for Business Analytics',
    title_fr: 'Excel pour l\'analyse commerciale',
    description: 'Master Excel for data-driven business decisions. Covers pivot tables, VLOOKUP, dashboards, and data visualization.',
    description_fr: 'Maîtrisez Excel pour des décisions commerciales basées sur les données. Couvre les tableaux croisés dynamiques, RECHERCHEV, tableaux de bord et visualisation.',
    url: 'https://datagenius.io/courses/excel-business',
    duration_minutes: 480,
    level: 'beginner',
    cost_type: 'freemium',
    category: 'data-analysis',
    referral_url: 'https://datagenius.io/courses/excel-business?ref=joblinca',
    featured: true,
  },
  {
    partner_name: 'DataGenius',
    title: 'SQL Fundamentals for Analysts',
    title_fr: 'Fondamentaux SQL pour analystes',
    description: 'Learn SQL from scratch. Query databases, join tables, aggregate data, and write reports.',
    description_fr: 'Apprenez SQL de zéro. Interrogez des bases de données, joignez des tables, agrégez des données et rédigez des rapports.',
    url: 'https://datagenius.io/courses/sql-fundamentals',
    duration_minutes: 360,
    level: 'beginner',
    cost_type: 'free',
    category: 'data-analysis',
    referral_url: 'https://datagenius.io/courses/sql-fundamentals?ref=joblinca',
    featured: false,
  },
  {
    partner_name: 'DataGenius',
    title: 'Power BI Dashboard Design',
    title_fr: 'Conception de tableaux de bord Power BI',
    description: 'Build interactive business dashboards with Microsoft Power BI. From data import to published reports.',
    description_fr: 'Créez des tableaux de bord interactifs avec Microsoft Power BI. De l\'import des données aux rapports publiés.',
    url: 'https://datagenius.io/courses/power-bi',
    duration_minutes: 420,
    level: 'intermediate',
    cost_type: 'paid',
    category: 'data-analysis',
    referral_url: 'https://datagenius.io/courses/power-bi?ref=joblinca',
    featured: true,
  },

  // Coursera
  {
    partner_name: 'Coursera',
    title: 'Google Project Management Certificate',
    title_fr: 'Certificat Google de gestion de projet',
    description: 'Earn a Google career certificate in project management. Learn Agile, Scrum, and stakeholder management.',
    description_fr: 'Obtenez un certificat Google en gestion de projet. Apprenez Agile, Scrum et la gestion des parties prenantes.',
    url: 'https://www.coursera.org/professional-certificates/google-project-management',
    duration_minutes: 6000,
    level: 'beginner',
    cost_type: 'freemium',
    category: 'project-management',
    referral_url: 'https://www.coursera.org/professional-certificates/google-project-management',
    featured: true,
  },
  {
    partner_name: 'Coursera',
    title: 'Digital Marketing & E-commerce',
    title_fr: 'Marketing digital et e-commerce',
    description: 'Google-backed certificate covering SEO, SEM, social media marketing, and e-commerce analytics.',
    description_fr: 'Certificat Google couvrant SEO, SEM, marketing sur les réseaux sociaux et analytics e-commerce.',
    url: 'https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce',
    duration_minutes: 4800,
    level: 'beginner',
    cost_type: 'freemium',
    category: 'marketing',
    referral_url: 'https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce',
    featured: false,
  },

  // edX
  {
    partner_name: 'edX',
    title: 'Introduction to Cloud Computing',
    title_fr: 'Introduction au Cloud Computing',
    description: 'Learn cloud fundamentals covering AWS, Azure, and GCP. Understand IaaS, PaaS, SaaS models.',
    description_fr: 'Apprenez les fondamentaux du cloud couvrant AWS, Azure et GCP. Comprenez les modèles IaaS, PaaS, SaaS.',
    url: 'https://www.edx.org/learn/cloud-computing',
    duration_minutes: 2400,
    level: 'beginner',
    cost_type: 'free',
    category: 'cloud',
    referral_url: 'https://www.edx.org/learn/cloud-computing',
    featured: true,
  },
  {
    partner_name: 'edX',
    title: 'Leadership and Communication',
    title_fr: 'Leadership et Communication',
    description: 'Develop essential leadership skills: team management, effective communication, and strategic thinking.',
    description_fr: 'Développez des compétences essentielles en leadership : gestion d\'équipe, communication efficace et pensée stratégique.',
    url: 'https://www.edx.org/learn/leadership',
    duration_minutes: 1800,
    level: 'intermediate',
    cost_type: 'freemium',
    category: 'leadership',
    referral_url: 'https://www.edx.org/learn/leadership',
    featured: false,
  },
  {
    partner_name: 'edX',
    title: 'Financial Accounting Fundamentals',
    title_fr: 'Fondamentaux de la comptabilité financière',
    description: 'Understand financial statements, double-entry bookkeeping, and accounting principles.',
    description_fr: 'Comprenez les états financiers, la comptabilité en partie double et les principes comptables.',
    url: 'https://www.edx.org/learn/financial-accounting',
    duration_minutes: 2100,
    level: 'beginner',
    cost_type: 'free',
    category: 'finance',
    referral_url: 'https://www.edx.org/learn/financial-accounting',
    featured: false,
  },

  // freeCodeCamp
  {
    partner_name: 'freeCodeCamp',
    title: 'Responsive Web Design',
    title_fr: 'Design Web Responsive',
    description: 'Learn HTML, CSS, Flexbox, Grid, and responsive design principles. Build 5 certification projects.',
    description_fr: 'Apprenez HTML, CSS, Flexbox, Grid et les principes du design responsive. Construisez 5 projets de certification.',
    url: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
    duration_minutes: 18000,
    level: 'beginner',
    cost_type: 'free',
    category: 'web-development',
    referral_url: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
    featured: true,
  },
  {
    partner_name: 'freeCodeCamp',
    title: 'JavaScript Algorithms & Data Structures',
    title_fr: 'Algorithmes JavaScript et structures de données',
    description: 'Master JavaScript fundamentals, ES6, regular expressions, debugging, and data structures.',
    description_fr: 'Maîtrisez les fondamentaux JavaScript, ES6, expressions régulières, débogage et structures de données.',
    url: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/',
    duration_minutes: 18000,
    level: 'intermediate',
    cost_type: 'free',
    category: 'web-development',
    referral_url: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/',
    featured: false,
  },
  {
    partner_name: 'freeCodeCamp',
    title: 'Machine Learning with Python',
    title_fr: 'Machine Learning avec Python',
    description: 'Learn TensorFlow, neural networks, NLP, and reinforcement learning. Build 5 ML projects.',
    description_fr: 'Apprenez TensorFlow, réseaux neuronaux, NLP et apprentissage par renforcement. Construisez 5 projets ML.',
    url: 'https://www.freecodecamp.org/learn/machine-learning-with-python/',
    duration_minutes: 18000,
    level: 'intermediate',
    cost_type: 'free',
    category: 'ai-ml',
    referral_url: 'https://www.freecodecamp.org/learn/machine-learning-with-python/',
    featured: true,
  },
  {
    partner_name: 'freeCodeCamp',
    title: 'UX Design Fundamentals',
    title_fr: 'Fondamentaux du design UX',
    description: 'Learn user research, wireframing, prototyping, and usability testing essentials.',
    description_fr: 'Apprenez la recherche utilisateur, le wireframing, le prototypage et les tests d\'utilisabilité.',
    url: 'https://www.freecodecamp.org/news/ui-ux-design-guide/',
    duration_minutes: 600,
    level: 'beginner',
    cost_type: 'free',
    category: 'design',
    referral_url: 'https://www.freecodecamp.org/news/ui-ux-design-guide/',
    featured: false,
  },
];
