'use client';

import { useState, useEffect, useRef } from 'react';
import { Download, Save, Loader2, CheckCircle, AlertCircle } from 'lucide-react';
import type { ResumeData } from '@/lib/resume';
import { RESUME_DRAFT_KEY } from '@/lib/resume';

interface PreviewStepProps {
  data: ResumeData;
  resumeId?: string;
}

export default function PreviewStep({ data, resumeId }: PreviewStepProps) {
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [message, setMessage] = useState<{ type: 'success' | 'error' | 'info'; text: string } | null>(null);
  // After the first save, subsequent saves update the same row instead of duplicating
  const [savedId, setSavedId] = useState<string | undefined>(resumeId);
  const autoGenerated = useRef(false);

  async function handleGenerate() {
    setGenerating(true);
    setMessage(null);
    try {
      const res = await fetch('/api/resume/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      });
      const result = await res.json();
      if (res.ok && result.dataUrl) {
        setPdfUrl(result.dataUrl);
      } else if (res.status === 401) {
        setMessage({ type: 'info', text: 'Sign in to generate and download your PDF.' });
      } else {
        setMessage({ type: 'error', text: result.error || 'Failed to generate PDF' });
      }
    } catch {
      setMessage({ type: 'error', text: 'Failed to generate PDF' });
    } finally {
      setGenerating(false);
    }
  }

  // Generate the preview automatically when the user reaches this step
  useEffect(() => {
    if (autoGenerated.current) return;
    autoGenerated.current = true;
    handleGenerate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function handleDownload() {
    if (!pdfUrl) return;
    const link = document.createElement('a');
    link.href = pdfUrl;
    link.download = `${data.fullName || 'resume'}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  async function handleSave() {
    setSaving(true);
    setMessage(null);
    try {
      const res = await fetch('/api/resume/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...data, resumeId: savedId }),
      });
      const result = await res.json();
      if (res.ok) {
        if (result.id) setSavedId(result.id);
        try {
          localStorage.removeItem(RESUME_DRAFT_KEY);
        } catch {
          // ignore
        }
        setMessage({
          type: 'success',
          text: savedId ? 'Resume updated.' : 'Resume saved to your account.',
        });
      } else if (res.status === 401) {
        setMessage({ type: 'info', text: 'Sign in to save your resume to your account.' });
      } else {
        setMessage({ type: 'error', text: result.error || 'Failed to save' });
      }
    } catch {
      setMessage({ type: 'error', text: 'Failed to save resume' });
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-semibold text-gray-100 mb-2">Preview & Download</h2>
        <p className="text-gray-400">Review your PDF resume, download it, or save it to your account.</p>
      </div>

      {/* Resume summary card */}
      <div className="bg-gray-800/50 border border-gray-700 rounded-xl p-6 space-y-4">
        <h3 className="text-lg font-semibold text-gray-100">{data.fullName || 'Your Name'}</h3>
        {data.title && <p className="text-gray-400">{data.title}</p>}
        <div className="text-sm text-gray-500 flex flex-wrap gap-3">
          {data.email && <span>{data.email}</span>}
          {data.phone && <span>{data.phone}</span>}
          {data.location && <span>{data.location}</span>}
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
          <div>
            <p className="text-gray-500">Experience</p>
            <p className="text-gray-200 font-medium">{data.experience.length} position{data.experience.length !== 1 ? 's' : ''}</p>
          </div>
          <div>
            <p className="text-gray-500">Education</p>
            <p className="text-gray-200 font-medium">{data.education.length} entr{data.education.length !== 1 ? 'ies' : 'y'}</p>
          </div>
          <div>
            <p className="text-gray-500">Skills</p>
            <p className="text-gray-200 font-medium">{data.skills.length} skill{data.skills.length !== 1 ? 's' : ''}</p>
          </div>
          <div>
            <p className="text-gray-500">Template</p>
            <p className="text-gray-200 font-medium capitalize">{data.template}</p>
          </div>
        </div>
      </div>

      {/* PDF preview */}
      {generating && !pdfUrl && (
        <div className="w-full h-[500px] border border-gray-700 rounded-xl flex flex-col items-center justify-center gap-3 text-gray-400">
          <Loader2 className="w-8 h-8 animate-spin text-blue-400" />
          <p className="text-sm">Generating preview...</p>
        </div>
      )}
      {pdfUrl && (
        <div className="w-full h-[500px] border border-gray-700 rounded-xl overflow-hidden">
          <iframe src={pdfUrl} className="w-full h-full" title="Resume PDF Preview" />
        </div>
      )}

      {message && (
        <div className={`flex items-center gap-2 p-3 rounded-lg border text-sm ${
          message.type === 'success'
            ? 'bg-green-500/10 border-green-500/20 text-green-400'
            : message.type === 'info'
              ? 'bg-blue-500/10 border-blue-500/20 text-blue-300'
              : 'bg-red-500/10 border-red-500/20 text-red-400'
        }`}>
          {message.type === 'success' ? (
            <CheckCircle className="w-4 h-4 shrink-0" />
          ) : (
            <AlertCircle className="w-4 h-4 shrink-0" />
          )}
          {message.text}
        </div>
      )}

      <div className="flex flex-wrap gap-3">
        <button
          type="button"
          onClick={handleGenerate}
          disabled={generating}
          className="inline-flex items-center gap-2 px-5 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50"
        >
          {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
          {generating ? 'Generating...' : 'Regenerate PDF'}
        </button>

        {pdfUrl && (
          <button
            type="button"
            onClick={handleDownload}
            className="inline-flex items-center gap-2 px-5 py-2.5 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
          >
            <Download className="w-4 h-4" />
            Download PDF
          </button>
        )}

        <button
          type="button"
          onClick={handleSave}
          disabled={saving}
          className="inline-flex items-center gap-2 px-5 py-2.5 bg-gray-600 text-white rounded-lg hover:bg-gray-500 transition-colors disabled:opacity-50"
        >
          {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
          {saving ? 'Saving...' : savedId ? 'Update Resume' : 'Save to Account'}
        </button>
      </div>
    </div>
  );
}
