-- Seed the 7 launch domains for Talent Challenges V2.
--
-- Each row is created in 'draft' status with an empty question bank.
-- Admin authors questions through the admin UI before flipping to 'active'.
-- starts_at / ends_at are placeholder values (will be overwritten by admin).

INSERT INTO public.talent_challenges (
  slug,
  title,
  title_fr,
  description,
  description_fr,
  challenge_type,
  domain,
  difficulty,
  starts_at,
  ends_at,
  timezone,
  status,
  max_ranked_attempts,
  top_n,
  config,
  access_tier,
  is_sponsored
) VALUES
  (
    'launch-teacher-basics',
    'Teaching Essentials',
    'Bases de l''Enseignement',
    'Core knowledge for classroom teachers: lesson planning, classroom management, and assessment basics.',
    'Connaissances de base pour les enseignants : planification des leçons, gestion de classe et évaluation.',
    'quiz',
    'teacher',
    'beginner',
    now(),
    now() + interval '7 days',
    'Africa/Douala',
    'draft',
    1,
    10,
    jsonb_build_object('questions', '[]'::jsonb, 'time_limit_seconds', 600, 'shuffle_questions', true),
    'free',
    false
  ),
  (
    'launch-accountant-basics',
    'Accounting Fundamentals',
    'Fondamentaux de la Comptabilité',
    'Bookkeeping, journal entries, trial balance, and basic financial statements for entry-level accounting roles.',
    'Tenue de comptes, écritures de journal, balance et états financiers de base pour les postes débutants.',
    'quiz',
    'accountant',
    'beginner',
    now(),
    now() + interval '7 days',
    'Africa/Douala',
    'draft',
    1,
    10,
    jsonb_build_object('questions', '[]'::jsonb, 'time_limit_seconds', 600, 'shuffle_questions', true),
    'free',
    false
  ),
  (
    'launch-admin-assistant-basics',
    'Administrative Assistant Skills',
    'Compétences d''Assistant Administratif',
    'Office workflows, document handling, scheduling, and professional communication.',
    'Flux de bureau, gestion de documents, planification et communication professionnelle.',
    'quiz',
    'admin_assistant',
    'beginner',
    now(),
    now() + interval '7 days',
    'Africa/Douala',
    'draft',
    1,
    10,
    jsonb_build_object('questions', '[]'::jsonb, 'time_limit_seconds', 600, 'shuffle_questions', true),
    'free',
    false
  ),
  (
    'launch-cashier-basics',
    'Cashier Operations',
    'Opérations de Caisse',
    'Cash handling, POS systems, customer interactions, and end-of-day reconciliation.',
    'Manipulation des espèces, systèmes de caisse, interactions clients et clôture de caisse.',
    'quiz',
    'cashier',
    'beginner',
    now(),
    now() + interval '7 days',
    'Africa/Douala',
    'draft',
    1,
    10,
    jsonb_build_object('questions', '[]'::jsonb, 'time_limit_seconds', 600, 'shuffle_questions', true),
    'free',
    false
  ),
  (
    'launch-nurse-basics',
    'Nursing Care Foundations',
    'Bases des Soins Infirmiers',
    'Vital signs, infection control, patient communication, and basic emergency response. Content reviewed by qualified nursing staff.',
    'Signes vitaux, contrôle des infections, communication patient et premiers secours. Contenu validé par du personnel infirmier qualifié.',
    'quiz',
    'nurse',
    'beginner',
    now(),
    now() + interval '7 days',
    'Africa/Douala',
    'draft',
    1,
    10,
    jsonb_build_object('questions', '[]'::jsonb, 'time_limit_seconds', 600, 'shuffle_questions', true),
    'free',
    false
  ),
  (
    'launch-customer-service-basics',
    'Customer Service Excellence',
    'Excellence du Service Client',
    'Active listening, complaint resolution, call etiquette, and product/service knowledge transfer.',
    'Écoute active, résolution de réclamations, étiquette téléphonique et transfert de connaissances produit/service.',
    'quiz',
    'customer_service',
    'beginner',
    now(),
    now() + interval '7 days',
    'Africa/Douala',
    'draft',
    1,
    10,
    jsonb_build_object('questions', '[]'::jsonb, 'time_limit_seconds', 600, 'shuffle_questions', true),
    'free',
    false
  ),
  (
    'launch-field-officer-basics',
    'Field & Community Work',
    'Travail de Terrain et Communautaire',
    'Survey administration, community mobilization, data collection ethics, and safety protocols.',
    'Administration d''enquêtes, mobilisation communautaire, éthique de collecte de données et protocoles de sécurité.',
    'quiz',
    'field_officer',
    'beginner',
    now(),
    now() + interval '7 days',
    'Africa/Douala',
    'draft',
    1,
    10,
    jsonb_build_object('questions', '[]'::jsonb, 'time_limit_seconds', 600, 'shuffle_questions', true),
    'free',
    false
  )
ON CONFLICT (slug) DO NOTHING;
